<style lang="scss">
    .privacy-policy {
        height: auto;
    }
</style>

<template>
    <div class="privacy-policy" :class="classObj">
        <h1>Privacy Policy</h1>
        <p>Edible Interfaces is a suite of public utilities whose use require no personal information. We do not store any user data at all. Any data generated by an Edible Interfaces app is stored in your browser cache or by a 3rd-party cloud provider such as Google or Dropbox.</p>
    </div>
</template>

<script>
    export default { name: 'privacy-policy'}
</script>
